# Generated by Django 5.2.6 on 2025-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='products',
            new_name='product',
        ),
    ]
